bind_addr = ":8085"
log_level = "debug"
database_url =  "host=3.64.98.51 port=5432 user=postgres password=Ps_123456 dbname=bta_new sslmode=disable"
session_key = "U7shDRc3Jl701yvX4Vq1vLTHQdnoJh5C9Mlmppy9ybonv3kY323LqKss2nGUeZvurHlC74MFFZlRsZTP+oa2c97PEN+ea8Pb8AvM="
